// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Naxam.Busuu.iOS.Social
{
	public partial class FilterView : UIViewController
	{
		public FilterView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

			//this.NavigationController.NavigationBar.Layer.ShadowRadius = 2;
			//this.NavigationController.NavigationBar.Layer.ShadowOpacity = 0.2f;
			//this.NavigationController.NavigationBar.Layer.ShadowOffset = new CoreGraphics.CGSize(2, 2);
		}
	}
}
