// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Core.ViewModels;
using MvvmCross.iOS.Views;
using Naxam.Busuu.Social.ViewModels;
using UIKit;

namespace Naxam.Busuu.iOS.Social
{
	[MvxFromStoryboard(StoryboardName = "Social")]
    public partial class FilterView : MvxViewController<FilterViewModel>
	{
		public FilterView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            this.Request = new MvxViewModelRequest<FilterViewModel>(null, null);

            base.ViewDidLoad();

            ViewShadow.Layer.ShadowRadius = 2;
			ViewShadow.Layer.ShadowOpacity = 0.3f;
			ViewShadow.Layer.ShadowOffset = new CoreGraphics.CGSize(2, 2);
		}
	}
}
