// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.iOS.Views;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Core.ViewModels;
using Naxam.Busuu.Social.ViewModels;
using UIKit;
using MvvmCross.Binding.iOS.Views;
using Naxam.Busuu.iOS.Social.Cells;

namespace Naxam.Busuu.iOS.Social.Views
{
	[MvxFromStoryboard(StoryboardName = "Social")]
    public partial class FriendsView : MvxViewController<FriendsViewModel>
	{
		public FriendsView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
	        Request = new MvxViewModelRequest<FriendsViewModel>(null, null);

			base.ViewDidLoad();

            MvxSimpleTableViewSource fSource = new MvxSimpleTableViewSource(FriendsTableView, typeof(FriendsCell), "FriendsCell");
            FriendsTableView.Source = fSource;			

            var setBinding = this.CreateBindingSet<FriendsView, FriendsViewModel>();
            setBinding.Bind(fSource).To(vm => vm.FriendsData);
			setBinding.Apply();

			FriendsTableView.ReloadData();
        }
	}
}
