// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.iOS.Views;
using UIKit;

namespace Naxam.Busuu.iOS.Social
{
	[MvxFromStoryboard(StoryboardName = "Social")]
	public partial class FriendsView : MvxViewController
	{
		public FriendsView (IntPtr handle) : base (handle)
		{
		}
	}
}
