// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Core.ViewModels;
using MvvmCross.iOS.Views;
using Naxam.Busuu.Social.ViewModels;
using UIKit;

namespace Naxam.Busuu.iOS.Social.Views
{
	[MvxFromStoryboard(StoryboardName = "Social")]
    public partial class FriendsView : MvxViewController<FriendsViewModel>
	{
		public FriendsView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
			this.Request = new MvxViewModelRequest<FriendsViewModel>(null, null);

			base.ViewDidLoad();
           
        }
	}
}
