// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Core.ViewModels;
using MvvmCross.iOS.Views;
using Naxam.Busuu.iOS.Start.Cells;
using Naxam.Busuu.iOS.Start.Common;
using Naxam.Busuu.Start.Model;
using Naxam.Busuu.Start.ViewModel;
using UIKit;

namespace Naxam.Busuu.iOS.Start.Views
{
    [MvxFromStoryboard(StoryboardName = "Start")]
    public partial class ChooseCountryView : MvxViewController<ChooseCountryViewModel>//, IUITableViewDataSource
	{
        //MvxObservableCollection<CountryModel> AllDataTable;

		public ChooseCountryView (IntPtr handle) : base (handle)
		{
		}
              
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

			ViewShadow.Layer.ShadowRadius = 2;
			ViewShadow.Layer.ShadowOpacity = 0.25f;
			ViewShadow.Layer.ShadowOffset = new CoreGraphics.CGSize(0, 2);

            var cSource = new ChooseCountryTableViewSource(ChooseCountryTableView);

            var setBinding = this.CreateBindingSet<ChooseCountryView, ChooseCountryViewModel>();
            setBinding.Bind(cSource).To(vm => vm.Countries);
            setBinding.Bind(cSource).For(vm => vm.SelectedItem).To(vm => vm.CountrySelected);
			setBinding.Apply();
           	
			ChooseCountryTableView.Source = cSource;
        }
	}
}
