// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.iOS.Views;
using Naxam.Busuu.Start.ViewModel;
using UIKit;

namespace Naxam.Busuu.iOS.Start.Views
{
    [MvxFromStoryboard(StoryboardName = "Start")]
    public partial class ChooseCountryView : MvxViewController<ChooseCountryViewModel>
	{
		public ChooseCountryView (IntPtr handle) : base (handle)
		{
		}
	}
}
