// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.iOS.Views;
using Naxam.Busuu.Start.ViewModel;
using UIKit;

namespace Naxam.Busuu.iOS.Start.Views
{
    [MvxFromStoryboard(StoryboardName = "Start")]
	public partial class ForgotPasswordView : MvxViewController<ForgotPasswordViewModel>
	{
		public ForgotPasswordView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

			ViewShadow.Layer.ShadowRadius = 2;
			ViewShadow.Layer.ShadowOpacity = 0.25f;
			ViewShadow.Layer.ShadowOffset = new CoreGraphics.CGSize(0, 2);

            btnSendLink.Layer.CornerRadius = btnSendLink.Frame.Height / 2;
        }
	}
}
