// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using MvvmCross.iOS.Views;
using MvvmCross.iOS.Views.Presenters.Attributes;
using Naxam.Busuu.Core.ViewModels;
using Naxam.Busuu.iOS.Core.CustomControls;

namespace Naxam.Busuu.iOS.Views
{
    [MvxFromStoryboard(StoryboardName = "Main")]
    [MvxRootPresentation(WrapInNavigationController = true)]
    public partial class MainTabBarView : MvxTabBarViewController<MainTabBarViewModel>, IMaterialTabBarDelegate
	{
        bool _isPresentedFirstTime = true;

		public MainTabBarView (IntPtr handle) : base (handle)
		{
		}

        MaterialTabBar _CustomTabBar;

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

		}



        public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);


			if (ViewModel != null && _isPresentedFirstTime)
			{               
				_isPresentedFirstTime = false;
				ViewModel.ShowInitialViewModelsCommand.Execute(null);

				//this.CreateBinding(TabBar.Items[1]).For(vm => vm.BadgeValue).To<NotificationViewModel>(vm => vm.NotificationCount).Apply();
				TabBar.Items[1].BadgeValue = "9";
                _CustomTabBar = new MaterialTabBar(TabBar, UIKit.UIColor.FromRGB(57, 169, 246))
                {
                    Delegate = this
                };
				//_CustomTabBar.UpdateBadge(1, "9");
			}
		}

        void IMaterialTabBarDelegate.SelectedIndex(MaterialTabBar tabbar, int index)
        {
            SelectedIndex = index;
        }
    }
}
