// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.iOS.Views;
using Naxam.Busuu.Learning.ViewModel;
using UIKit;

namespace Naxam.Busuu.iOS.Learning.Views
{
    [MvxFromStoryboard(StoryboardName = "Learning")]
    public partial class PremiumView : MvxViewController<PremiumViewModel>
	{
		public PremiumView (IntPtr handle) : base (handle)
		{
		}
	}
}
