// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.iOS.Views;
using MvvmCross.iOS.Views.Presenters.Attributes;
using Naxam.Busuu.Notification.ViewModels;
using UIKit;

namespace Naxam.Busuu.iOS.Notification.Views
{
	[MvxFromStoryboard(StoryboardName = "Notification")]
	[MvxTabPresentation(WrapInNavigationController = true, TabIconName = "notifications_tab_icon", TabName = "Notifications", TabSelectedIconName = "notifications_tab_icon_selected")]
	public partial class NotificationView : MvxViewController<NotificationViewModel>
	{
		public NotificationView (IntPtr handle) : base (handle)
		{
		}
	}
}
