// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.iOS.Views;
using MvvmCross.iOS.Views.Presenters.Attributes;
using Naxam.Busuu.Profile.ViewModel;
using UIKit;

namespace Naxam.Busuu.iOS.Profile.Views
{
	[MvxFromStoryboard(StoryboardName = "Profile")]
    [MvxTabPresentation(WrapInNavigationController = true, TabIconName = "profile_tab_icon", TabName = "Profile", TabSelectedIconName = "profile_tab_icon_selected")]
	public partial class RegisterView : MvxViewController<RegisterViewModel>
	{
		public RegisterView (IntPtr handle) : base (handle)
		{
		}
	}
}
