// This file has been autogenerated from a class added in the UI designer.

using System;

using MvvmCross.Binding.BindingContext;
using MvvmCross.Binding.iOS.Views;
using Naxam.Busuu.iOS.Notification.Common;
using Naxam.Busuu.Notification.Models;
using UIKit;

namespace Naxam.Busuu.iOS.Notification.Cells
{
	public partial class NotificationCell : MvxTableViewCell
	{
        readonly MvxImageViewLoader _loaderImageUser;

		public NotificationCell (IntPtr handle) : base(handle)
		{
            _loaderImageUser = new MvxImageViewLoader(() => this.imgUser);

			this.DelayBind(() =>
			{
                var setBinding = this.CreateBindingSet<NotificationCell, NotificationModel>();
                setBinding.Bind(_loaderImageUser).To(n => n.ImgUser).WithConversion(new MyMvxConverter.ImageUriValueConverter(), null);
                setBinding.Bind(lblDetail).For(n => n.AttributedText).To(n => n.Details).WithConversion(new MyMvxConverter.DetailValueConverter(), null);
                setBinding.Bind(lblTime).To(n => n.Time).WithConversion(new MyMvxConverter.DatetimeStringValueConverter(), null);
                setBinding.Bind(ContentView).For(n => n.BackgroundColor).To(n => n.Check).WithConversion(new MyMvxConverter.ColorValueConverter(), null);
                setBinding.Apply();
			});
                      
		}

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();

            imgUser.Layer.CornerRadius = imgUser.Frame.Width / 2;
        }
	}
}
