// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Binding.iOS.Views;
using Naxam.Busuu.iOS.Notification.Common;
using Naxam.Busuu.Notification.Models;
using UIKit;

namespace Naxam.Busuu.iOS.Notification.Cells
{
	public partial class NotificationCell : MvxTableViewCell
	{
        readonly MvxImageViewLoader _loaderImageUser;

		public NotificationCell (IntPtr handle) : base (handle)
		{
            _loaderImageUser = new MvxImageViewLoader(() => this.imgUser);

			this.DelayBind(() =>
			{
                var setBinding = this.CreateBindingSet<NotificationCell, NotificationModel>();
                setBinding.Bind(_loaderImageUser).To(n => n.ImgUser).WithConversion(new MyMvxConverter.ImageUriValueConverter(), null);
                setBinding.Bind(lblDetail).To(n => n.Details);
                setBinding.Bind(lblTime).To(n => n.Time);
                setBinding.Bind(ContentView).For(n => n.BackgroundColor).To(n => n.Check).WithConversion(new MyMvxConverter.ColorValueConverter(), null);
				setBinding.Apply();
			});
		}

        public override void LayoutSubviews()
        {
            base.LayoutSubviews();

            var firstAttributes = new UIStringAttributes
            {
                Font = UIFont.BoldSystemFontOfSize(14f)
			};

			var prettyString = new NSMutableAttributedString(lblDetail.Text);
			prettyString.SetAttributes(firstAttributes.Dictionary, new NSRange(0, 14));

            lblDetail.AttributedText = prettyString;
        }
	}
}
