// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Binding.iOS.Views;
using Naxam.Busuu.Learning.Model;
using UIKit;

namespace Naxam.Busuu.iOS.Learning
{
    public partial class SubLessonTableViewCell : MvxTableViewCell
    {
        public SubLessonTableViewCell(IntPtr handle) : base(handle)
        {
        }

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();
            this.DelayBind(() =>
          {
              var bindingSet = this.CreateBindingSet<SubLessonTableViewCell, TopicModel>();
              bindingSet.Apply();
          });
            imgSubLesson.Layer.CornerRadius = imgSubLesson.Bounds.Size.Height / 2;
            imgSubLesson.Layer.BackgroundColor = UIColor.White.CGColor;
        }
    }
}
