// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.iOS.Views;
using Naxam.Busuu.Profile.ViewModel;
using UIKit;

namespace Naxam.Busuu.iOS.Profile.Views
{
	[MvxFromStoryboard(StoryboardName = "Profile")]
	public partial class RegisterView : MvxViewController<RegisterViewModel>
	{
		public RegisterView (IntPtr handle) : base (handle)
		{
		}
	}
}
