// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.iOS.Views;
using Naxam.Busuu.Profile.ViewModel;
using UIKit;

namespace Naxam.Busuu.iOS.Profile.Views
{
    [MvxFromStoryboard(StoryboardName = "Profile")]
    public partial class StartPageView : MvxViewController<StartPageViewModel>
	{
		public StartPageView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            this.NavigationController.NavigationBarHidden = true;
         
            btnGetStarted.Layer.CornerRadius = btnGetStarted.Frame.Height / 2;

            var setBinding = this.CreateBindingSet<StartPageView, StartPageViewModel>();
            setBinding.Bind(btnGetStarted).To(vm => vm.GetStartedCommand);
            setBinding.Bind(btnLogin).To(vm => vm.LoginCommand);
			setBinding.Apply();
        }

        public override void ViewWillLayoutSubviews()
        {
            base.ViewWillLayoutSubviews();

			this.NavigationController.NavigationBarHidden = true;
		}
	}
}
