// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.iOS.Views;
using Naxam.Busuu.Core.ViewModels;
using Naxam.Busuu.iOS.Social.Views;
using UIKit;

namespace Naxam.Busuu.iOS.Core.Views
{
    [MvxFromStoryboard(StoryboardName = "Core")]
    public partial class MainTabBarView : MvxTabBarViewController<MainTabBarViewModel>
	{
        private bool _isPresentedFirstTime = true;

		public MainTabBarView (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);

			if (ViewModel != null && _isPresentedFirstTime)
			{
				_isPresentedFirstTime = false;
				ViewModel.ShowInitialViewModelsCommand.Execute(null);
			}
		}		
	}
}
