// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Core.ViewModels;
using MvvmCross.iOS.Views;
using Naxam.Busuu.Social.ViewModels;
using UIKit;

namespace Naxam.Busuu.iOS.Social
{
	[MvxFromStoryboard(StoryboardName = "Social")]
    public partial class FilterView : MvxViewController<FilterViewModel>
	{
        UIBarButtonItem btndone;

		public FilterView (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

			btndone = new UIBarButtonItem("DONE", UIBarButtonItemStyle.Plain, (sender, args) => { });
			NavigationItem.RightBarButtonItem = btndone;

            ViewShadow.Layer.ShadowRadius = 2;
			ViewShadow.Layer.ShadowOpacity = 0.25f;
			ViewShadow.Layer.ShadowOffset = new CoreGraphics.CGSize(0, 2);

            var setBinding = this.CreateBindingSet<FilterView, FilterViewModel>();
			setBinding.Bind(btndone).For("Clicked").To(vm => vm.btnDoneCommand);
			setBinding.Apply();

            btndone.Enabled = false;
		}
	}
}
