// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Core.ViewModels;
using MvvmCross.iOS.Views;
using MvvmCross.iOS.Views.Presenters.Attributes;
using Naxam.Busuu.iOS.Notification.Common;
using Naxam.Busuu.Notification.ViewModels;
using UIKit;

namespace Naxam.Busuu.iOS.Notification.Views
{
	[MvxFromStoryboard(StoryboardName = "Notification")]
    [MvxTabPresentation(WrapInNavigationController = true, TabIconName = "notifications_tab_icon", TabName = "Notifications", TabSelectedIconName = "notifications_tab_icon_selected")]
	public partial class NotificationView : MvxViewController<NotificationViewModel>
	{
        public NotificationView()
        {
            this.TabBarController.TabBar.Items[1].BadgeValue = "5";
        }

        public NotificationView(IntPtr handle) : base(handle)
        {

		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var nSource = new NotificationTableViewSource(NotificationTableView);

            var setBinding = this.CreateBindingSet<NotificationView, NotificationViewModel>();
            setBinding.Bind(nSource).To(vm => vm.NotificationData);
            setBinding.Bind(nSource).For(vm => vm.SelectionChangedCommand).To(vm => vm.ViewNotificationCommand);
			setBinding.Apply();

			NotificationTableView.RowHeight = UITableView.AutomaticDimension;
			NotificationTableView.EstimatedRowHeight = 72f;
			NotificationTableView.Source = nSource;

            this.TabBarController.TabBar.Items[1].BadgeValue = null;	
        }
	}
}
