// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Globalization;
using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Binding.iOS.Views;
using MvvmCross.Platform.Converters;
using Naxam.Busuu.Social.Models;
using UIKit;

namespace Naxam.Busuu.iOS.Social.Cells
{
	public partial class FriendsCell : MvxTableViewCell
	{
        private readonly MvxImageViewLoader _loaderImageUser;
		private readonly MvxImageViewLoader _loaderImgLearn;

		public FriendsCell (IntPtr handle) : base (handle)
		{
            _loaderImageUser = new MvxImageViewLoader(() => this.imgUserAvatar);
			_loaderImgLearn = new MvxImageViewLoader(() => this.imgLan);

			this.DelayBind(() =>
			{
                var setBinding = this.CreateBindingSet<FriendsCell, FriendsModel>();
				setBinding.Bind(_loaderImageUser).To(d => d.Avatar).WithConversion(new ImageUriValueConverter(), null);
                setBinding.Bind(lblUserName).To(d => d.Star);
				setBinding.Bind(lblCountry).To(d => d.Country);
                setBinding.Bind(_loaderImgLearn).To(d => d.ImageLearn).WithConversion(new ImageUriValueConverter(), null);
                setBinding.Bind(textLan).To(d => d.TextLearn);
				setBinding.Apply();
			});
		}	
	}
}
